name: Docker

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-base:
    uses: ./.github/workflows/docker-build.yml
  build-mongodb:
    needs: [build-base]
    uses: ./.github/workflows/docker-build.yml
    with:
      tag-suffix: -mongodb
      context: ./prepost_strategies/mongodb
      base-image: ${{ needs.build-base.outputs.image }}
  build-mysql:
    needs: [build-base]
    uses: ./.github/workflows/docker-build.yml
    with:
      tag-suffix: -mysql
      context: ./prepost_strategies/mysql
      base-image: ${{ needs.build-base.outputs.image }}
  build-postgres:
    needs: [build-base]
    uses: ./.github/workflows/docker-build.yml
    with:
      tag-suffix: -postgres
      context: ./prepost_strategies/postgres
      base-image: ${{ needs.build-base.outputs.image }}
  build-mongodb-mysql:
    needs: [build-mongodb]
    uses: ./.github/workflows/docker-build.yml
    with:
      tag-suffix: -mongodb-mysql
      context: ./prepost_strategies/mysql
      base-image: ${{ needs.build-mongodb.outputs.image }}
  build-mongodb-postgres:
    needs: [build-mongodb]
    uses: ./.github/workflows/docker-build.yml
    with:
      tag-suffix: -mongodb-postgres
      context: ./prepost_strategies/postgres
      base-image: ${{ needs.build-mongodb.outputs.image }}
  build-mongodb-mysql-postgres:
    needs: [build-mongodb-mysql]
    uses: ./.github/workflows/docker-build.yml
    with:
      tag-suffix: -mongodb-mysql-postgres
      context: ./prepost_strategies/postgres
      base-image: ${{ needs.build-mongodb-mysql.outputs.image }}
  build-mysql-postgres:
    needs: [build-mysql]
    uses: ./.github/workflows/docker-build.yml
    with:
      tag-suffix: -mysql-postgres
      context: ./prepost_strategies/postgres
      base-image: ${{ needs.build-mysql.outputs.image }}