name: Docker Test Jobs

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string

jobs:
  test:
    strategy:
      matrix:
        database: [default, mongodb, mysql, postgres]
    uses: ./.github/workflows/docker-test.yml
    with:
      image-name: ${{ inputs.image-name }}
      image-type: ${{ matrix.database }}