name: Build
on: 
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with: 
          submodules: true
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v1
      - name: Build Images
        run: |
            set +o pipefail
            ./buildscripts/buildSupportedAlpineImages.sh
      - name: Test Images
        run: ./buildscripts/testSupportedAlpineImages.sh

