name: Build
on: 
  push:
    branches:
      - master
    tags: 
      - /^\d+(\.\d+)+$/
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with: 
          submodules: true
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v1
      - name: Build Images
        run: |
            set +o pipefail
            ./buildscripts/buildSupportedAlpineImages.sh
      - name: Test Images
        run: ./buildscripts/testSupportedAlpineImages.sh
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Images to DockerHub
        run: ./buildscripts/releaseSupportedAlpineImages.sh
